allowBuilds:
  esbuild: false
  onnxruntime-node: true
  protobufjs: true
  sharp: false
  workerd: true
minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.11.0'
  - '@astrojs/markdown-satteri@0.4.0'
  - astro@7.2.10
