name = "freeremovebg"
compatibility_date = "2025-06-01"
main = "./worker/index.js"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "freeremovebg.com", custom_domain = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"

not_found_handling = "404-page"

run_worker_first = ["/"]

[env.staging]
name = "freeremovebg-staging"
workers_dev = false
routes = [
  { pattern = "staging.freeremovebg.com", custom_domain = true }
]
run_worker_first = true

[env.staging.vars]
ENVIRONMENT = "staging"