// AUTO-GENERATED by scripts/gen-region-map.mjs — do not edit by hand.
// Run `pnpm i18n:regionmap` after changing src/i18n/languages.json.
//
// Mirrors REGION_MAP / SUPPORTED_CODES from src/i18n/config.ts so the Worker
// shares a single source of truth with the Astro build.

/** ISO 3166-1 country code -> language sub-route. */
export const regionMap = {
  "ES": "es",
  "MX": "es",
  "AR": "es",
  "CO": "es",
  "CL": "es",
  "PE": "es",
  "VE": "es",
  "EC": "es",
  "GT": "es",
  "CU": "es",
  "BO": "es",
  "DO": "es",
  "HN": "es",
  "PY": "es",
  "SV": "es",
  "NI": "es",
  "CR": "es",
  "PA": "es",
  "UY": "es",
  "IN": "hi",
  "NP": "ne",
  "BD": "bn",
  "CN": "zh",
  "TW": "zh",
  "HK": "zh",
  "SG": "zh",
  "MO": "zh",
  "SA": "ar",
  "AE": "ar",
  "EG": "ar",
  "QA": "ar",
  "KW": "ar",
  "OM": "ar",
  "BH": "ar",
  "JO": "ar",
  "IQ": "ar",
  "DZ": "ar",
  "MA": "ar",
  "TN": "ar",
  "LY": "ar",
  "BR": "pt",
  "PT": "pt",
  "AO": "pt",
  "MZ": "pt",
  "FR": "fr",
  "BE": "fr",
  "CD": "fr",
  "CI": "fr",
  "SN": "fr",
  "CM": "fr",
  "DE": "de",
  "AT": "de",
  "CH": "de",
  "RU": "ru",
  "BY": "ru",
  "KZ": "ru",
  "KG": "ru",
  "JP": "ja",
  "ID": "id",
};

/** Every supported language code, English ("en") included. */
export const supportedCodes = [
  "en",
  "es",
  "hi",
  "ne",
  "bn",
  "zh",
  "ar",
  "pt",
  "fr",
  "de",
  "ru",
  "ja",
  "id",
];

/** The default language served at the site root. */
export const defaultLang = "en";

/** Cookie that persists an explicit user language choice. */
export const langCookie = "lang";
